# Generated by Django 4.1.1 on 2023-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_panel',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='static_panel',
            name='measurement',
            field=models.IntegerField(default=0),
        ),
    ]
