# Generated by Django 4.1.1 on 2023-04-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0002_static_panel_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='static_panel',
            name='current',
            field=models.FloatField(default=0),
        ),
    ]
