# Generated by Django 4.1.1 on 2023-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0004_alter_static_panel_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dinamic_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.FloatField(default=0)),
                ('intensity1', models.FloatField(default=0)),
                ('intensity2', models.FloatField(default=0)),
                ('intensity3', models.FloatField(default=0)),
                ('intensity4', models.FloatField(default=0)),
                ('intensity5', models.FloatField(default=0)),
                ('intensity6', models.FloatField(default=0)),
                ('intensity7', models.FloatField(default=0)),
                ('intensity8', models.FloatField(default=0)),
                ('intensity9', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
            ],
        ),
    ]
